"""initial schema

Revision ID: a62077b1d02b
Revises: 
Create Date: 2026-07-07 01:54:58.636660
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a62077b1d02b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('status', sa.Enum('QUEUED', 'VALIDATING', 'UPLOADING', 'TRANSCRIBING', 'CLEANING', 'SUMMARIZING', 'EXTRACTING_ACTIONS', 'COMPLETED', 'FAILED', name='job_status'), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('audio_format', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stage', sa.Enum('VALIDATION', 'TRANSCRIPTION', 'CLEANING', 'SUMMARIZATION', 'CHECKLIST', name='stage_name'), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('processing_logs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('VALIDATION', 'TRANSCRIPTION', 'CLEANING', 'SUMMARIZATION', 'CHECKLIST', name='stage_name'), nullable=True),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='log_level'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_logs_job_id'), 'processing_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_processing_logs_stage'), 'processing_logs', ['stage'], unique=False)
    op.create_table('summaries',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('meeting_title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('agenda', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_job_id'), 'summaries', ['job_id'], unique=True)
    op.create_table('transcripts',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('VALIDATION', 'TRANSCRIPTION', 'CLEANING', 'SUMMARIZATION', 'CHECKLIST', name='stage_name'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_job_id'), 'transcripts', ['job_id'], unique=True)
    op.create_table('action_items',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('deadline', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', name='action_item_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_job_id'), 'action_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_action_items_summary_id'), 'action_items', ['summary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_items_summary_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_job_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_transcripts_job_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_summaries_job_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_processing_logs_stage'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_job_id'), table_name='processing_logs')
    op.drop_table('processing_logs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
